"""
Compounding-uncertainty stress test (reviewer weakness #1): how much of the between-school
priority ranking is real vs generated by the surface assumptions? We sweep the three uncertain
surface parameters over Low/Base/High simultaneously (3x3x3 = 27 settings) and measure how stable
the top-decile priority set is relative to the base case.

  Parameter        Low    Base   High
  Road increment A   3      5      8     (ug/m3)
  Decay length  L  100    150    250     (m)
  Infiltration shift -0.10  0    +0.10   (added to class factors 0.50/0.65/0.80, clipped)

Surface: indoor = (bg + A*exp(-dist/L)) * F_inf.  Index = mean of normalised
[indoor, envelope(F_inf class), -RWI, child]. Output: data/pipeline/parameter_sensitivity.csv (Table S19).
"""
import os, csv, math, sys, itertools
import numpy as np
sys.stdout.reconfigure(encoding="utf-8", errors="replace")
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", ".."))
OUT = os.path.join(ROOT, "data", "pipeline")
_child = {}
for r in csv.DictReader(open(os.path.join(OUT, "child_regional.csv"), encoding="utf-8")):
    _child.setdefault(r["city"], []).append(float(r["child_u20"]))
# (exposure_csv, rwi_csv, embassy-FEM background)
CITIES = {
 "Tashkent": ("giga_exposure_tashkent.csv","tashkent_rwi.csv",37.9),
 "Almaty":   ("giga_exposure_almaty.csv","rwi_almaty.csv",34.2),
 "Astana":   ("giga_exposure_astana.csv","rwi_astana.csv",18.5),
 "Bishkek":  ("giga_exposure_bishkek.csv","rwi_bishkek.csv",35.6),
 "Ashgabat": ("giga_exposure_ashgabat.csv","rwi_ashgabat.csv",22.8),
 "Dushanbe": (os.path.join("..","..","scripts","legacy_v1","b1d_dushanbe_school_exposure.csv"),"rwi_dushanbe.csv",53.3),
}
def norm(x):
    x=np.asarray(x,float); return (x-x.min())/(x.max()-x.min()) if x.max()>x.min() else x*0
def load_rwi(p):
    rows=list(csv.DictReader(open(os.path.join(OUT,p),encoding="utf-8")))
    return (np.array([float(r["lat"]) for r in rows]),np.array([float(r["lon"]) for r in rows]),np.array([float(r["rwi"]) for r in rows]))
GRID=list(itertools.product([3.,5.,8.],[100.,150.,250.],[-0.10,0.0,0.10]))
print(f"{'Capital':9}{'k':>4} | base via-eq | worst-case top-decile overlap vs base (27 settings) | via-eq range")
print("-"*92)
rows=[]
for city,(ecsv,rcsv,bg) in CITIES.items():
    ep=os.path.normpath(os.path.join(OUT,ecsv)) if str(ecsv).startswith("..") else os.path.join(OUT,ecsv)
    sch=list(csv.DictReader(open(ep,encoding="utf-8")))
    lat=np.array([float(s["lat"]) for s in sch]); lon=np.array([float(s["lon"]) for s in sch])
    dist=np.array([float(s["dist_m"]) for s in sch]); infil=np.array([float(s["infiltration"]) for s in sch])
    child=np.array(_child[city],float)
    rla,rlo,rv=load_rwi(rcsv)
    rwi_at=np.array([rv[int(np.argmin((rla-la)**2+((rlo-lo)*math.cos(math.radians(la)))**2))] for la,lo in zip(lat,lon)])
    env=norm(infil); dep=norm(-rwi_at); ch=norm(child); k=max(1,len(sch)//10)
    def prio(A,L,sh):
        f=np.clip(infil+sh,0.30,0.95)
        indoor=(bg+A*np.exp(-dist/L))*f
        idx=(norm(indoor)+env+dep+ch)/4.0
        return set(np.argsort(-idx)[:k].tolist()), idx, set(np.argsort(-indoor)[:k].tolist())
    base_set,_,base_oe=prio(5.,150.,0.0); base_ve=k-len(base_set&base_oe)
    overlaps=[]; ves=[]
    for A,L,sh in GRID:
        s,_,oe=prio(A,L,sh); overlaps.append(len(s&base_set)); ves.append(k-len(s&oe))
    worst=min(overlaps)
    print(f"{city:9}{k:>4} | {base_ve}/{k:<8} | worst {worst}/{k} ({100*worst//k}%) identical | {min(ves)}-{max(ves)}/{k}")
    rows.append({"capital":city,"k":k,"base_via_equity":f"{base_ve}/{k}",
                 "worst_overlap":f"{worst}/{k}","worst_overlap_pct":round(100*worst/k),
                 "via_equity_min":min(ves),"via_equity_max":max(ves)})
with open(os.path.join(OUT,"parameter_sensitivity.csv"),"w",newline="",encoding="utf-8") as f:
    w=csv.DictWriter(f,fieldnames=list(rows[0].keys())); w.writeheader(); w.writerows(rows)
print("saved parameter_sensitivity.csv")
